### ISSUE TITLE
 decimal data type error

### ISSUE THREAD

**Issue by darrenchinesedba** [tarantool/mysql-tarantool-replication#28] opened 2020-07-01 03:54 UTC
Tarantool reported null binlog position. Dumping tables...
[2020-06-30 17:23:29] E Slave::create_table(): class name don't exist for type: 246
[2020-06-30 17:23:29] E Error in reading binlogs: Slave::create_table(): error in field 'bet_money'

bet_money is  decimal(20,4)

**Comment by Totktonada** [comment] 2020-07-01 15:33
Duplicate of #18, which was not closed in fact. I'll reopen it.

**Closed by Totktonada** 2020-07-01 15:33 UTC
Labels: bug
