### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by pavelnemirovsky** [tarantool/mysql-tarantool-replication#14] opened 2017-08-13 18:54 UTC
Hi,
can you please elaborate why MariaDB (based on mysql 5.6) is not supported?
Thanks in advance,
P

**Comment by smarek** [comment] 2019-05-05 19:03
FYI MariaDB solution https://gist.github.com/smarek/d88a870128cdda948be70eb3f93d4c92

**Comment by pavelnemirovsky** [comment] 2019-05-06 18:38
@smarek thx a lot

**Comment by Totktonada** [comment] 2020-12-20 23:39
Duplicate of #4.

**Closed by Totktonada** 2020-12-20 23:39 UTC
